print ("RESPONDA LAS SIGUIENTES PREGUNTAS")

nombre1=input("Escriba sus dos nombres completos:   ")
apellido=input("Escriba sus dos apellidos completos:   ")
nombre2=input("Escriba los dos nombres completos de su amado compañero:"   )
apellido2=input("Escriba los dos apellidos de su amado compañero:    ")

print ("Ahora bien", nombre1,apellido, "Conteste las siguientes preguntas")
pregunta1=input("¿Ama usted a su amado antes mencionado?")
pregunta2=input("¿Desea vivir el resto de su vida con Andres Eduardo Alvarez Torres?  ")
pregunta3=input("¿Promete no volver a ponerse tan pero tan bravisima con su Amando?   ")
print ("TOMANDO EN CONSIDERACION TODAS SUS RESPUESTAS")
pregunta4=input("Andres desea hacerle una pregunta, ¿quiere qque le haga esa pregunta? (responda si o no):"   )
print ("la pregunta es")
pregunta5=input("¿QUIERES CASARTE CONMIGO?"   )
print ("SI LA PRESPUESTA ES SI ENTONCES VOLTEA A VER A TU AMADO")
print ("ESPERO QUE SEAMOS FELICES POR SIEMPRE")
print (nombre1,apellido, "y", nombre2,apellido2)
print ("Barquisimeto hoy 12 de abril de 2022")

